/**
 * GET /sitemap.xml [Master_Prompt v7.0 §20.4]
 * Serves sitemap from R2 (generated daily by cron).
 * Falls back to a basic sitemap if R2 key not found.
 */
import type { APIContext } from 'astro';
import { getEnv } from '../../lib/env';

export const prerender = true;

export async function GET(context: APIContext) {
  const env = getEnv(context);
  const site = 'https://zabirboutiques.com';

  // Try R2 first (generated by daily cron)
  if (env.MEDIA) {
    const obj = await env.MEDIA.get('sitemap.xml');
    if (obj) {
      return new Response(await obj.text(), {
        headers: { 'Content-Type': 'application/xml; charset=utf-8' },
      });
    }
  }

  // Fallback: basic sitemap from D1
  const products = await env.DB
    .prepare(`SELECT slug, updated_at FROM products WHERE status = 'published' ORDER BY updated_at DESC LIMIT 50000`)
    .all<{ slug: string; updated_at: string }>();

  const categories = await env.DB
    .prepare(`SELECT slug, updated_at FROM categories ORDER BY updated_at DESC LIMIT 1000`)
    .all<{ slug: string; updated_at: string }>();

  const urls = [
    `<url><loc>${site}/</loc><changefreq>daily</changefreq><priority>1.0</priority></url>`,
    ...((products.results ?? []).map((p) =>
      `<url><loc>${site}/products/${p.slug}</loc><lastmod>${p.updated_at?.slice(0, 10)}</lastmod><changefreq>weekly</changefreq><priority>0.8</priority></url>`
    )),
    ...((categories.results ?? []).map((c) =>
      `<url><loc>${site}/categories/${c.slug}</loc><lastmod>${c.updated_at?.slice(0, 10)}</lastmod><changefreq>weekly</changefreq><priority>0.6</priority></url>`
    )),
    `<url><loc>${site}/about</loc><changefreq>monthly</changefreq><priority>0.3</priority></url>`,
    `<url><loc>${site}/privacy</loc><changefreq>yearly</changefreq><priority>0.1</priority></url>`,
    `<url><loc>${site}/terms</loc><changefreq>yearly</changefreq><priority>0.1</priority></url>`,
    `<url><loc>${site}/return-policy</loc><changefreq>yearly</changefreq><priority>0.1</priority></url>`,
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>`;

  return new Response(xml, {
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  });
}
